### ISSUE TITLE
2020.3.11一键生成报错

### ISSUE THREAD

**Issue by coder-lipenghui** [qq576067421/cshotfix#3]
unity版本 2020.3.11f1c1

Unity.Profiling.LowLevel.Unsafe.ProfilerUnsafeUtility
System.IntPtr
一键生成注入导出失败，System.NotSupportedException: Specified method is not supported.

**Comment by qq576067421** [comment]
全文搜索“blackNamespaceList”，在这个字段有大量需要过滤的黑名单，依葫芦画瓢添加 “Unity.Profiling.LowLevel.Unsafe”这个命名空间

**Comment by qq576067421** [comment]
![QQ图片20210709175021](https://user-images.githubusercontent.com/9191819/125059659-256a0a00-e0de-11eb-8fcd-b1d67afd54c7.png)

**Comment by coder-lipenghui** [comment]
在blackNamespaceList 添加了Unity.Profiling.LowLevel.Unsafe解决了报错
